--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PresentKim/banner-factory
branches:
  - main
projects:
  banner-factory:
    model: virion
    type: library
    lint:
      phpstan: false
...
